apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eli-dev
resources:
  - postgres.yaml
  - redis.yaml
  - backend.yaml
  - frontend.yaml
  - route.yaml
images:
  - name: ghcr.io/fashinski/guestbook-backend
    newName: ghcr.io/fashinski/guestbook-backend
    newTag: 03f1480
  - name: ghcr.io/fashinski/guestbook-frontend
    newName: ghcr.io/fashinski/guestbook-frontend
    newTag: 03f1480
