apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres.yaml
  - redis.yaml
  - backend.yaml
  - frontend.yaml
  - route.yaml
  - hpa-backend.yaml
  - hpa-frontend.yaml
images:
  - name: ghcr.io/fashinski/guestbook-backend
    newName: ghcr.io/fashinski/guestbook-backend
    newTag: 255c3ae
  - name: ghcr.io/fashinski/guestbook-frontend
    newName: ghcr.io/fashinski/guestbook-frontend
    newTag: 255c3ae
